/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-16 00:28:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682400015840L));
    _jspx_dependants.put("jar:file:/C:/multi/06.spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/step12_Stocks/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>SB Admin 2 - S</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template-->\r\n");
      out.write("    <link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template-->\r\n");
      out.write("    <link href=\"/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("                <!-- Topbar -->\r\n");
      out.write("                \r\n");
      out.write("          \r\n");
      out.write("                \r\n");
      out.write("                <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("                    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("                        <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Topbar Search -->\r\n");
      out.write("                    <form\r\n");
      out.write("                     	class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("                        <span>STOCKS MARKET</span>\r\n");
      out.write("                    </form>\r\n");
      out.write("				  <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"/index\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">Go back to main page</div>\r\n");
      out.write("        		    </a>\r\n");
      out.write("				\r\n");
      out.write("                    <!-- Topbar Navbar -->\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Nav Item - User Information -->\r\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                <img class=\"img-profile rounded-circle\"\r\n");
      out.write("                                    src=\"/resources/img/undraw_profile.svg\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Dropdown - User Information -->\r\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("                                aria-labelledby=\"userDropdown\">\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                                    Profile\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                                    Settings\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                                    Activity Log\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"/logout\" data-toggle=\"modal\" data-target=\"#logoutModal\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                                    Logout\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Begin Page Content -->\r\n");
      out.write("                 <!-- Nav Item - Tables -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("					\r\n");
      out.write("                    <!-- Page Heading -->\r\n");
      out.write("                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("                  \r\n");
      out.write("                        <h1 class=\"h3 mb-0 text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.company_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Content Row -->\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                         \r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-primary shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                           <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">\r\n");
      out.write("                                               	계좌금액</div>\r\n");
      out.write(" 										<div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.user_money}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">\r\n");
      out.write("                                               	거래가격</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ stocks.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("₩</div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            \r\n");
      out.write("                                            <!-- 등락율  ----------------------------------------------------------------------                      -->                                        \r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"countBox\">\r\n");
      out.write("										        <p class=\"countNumber\">0%</p>\r\n");
      out.write("										        <div class=\"countButtonWrap\">\r\n");
      out.write("										            <button class=\"generate\">Refresh</button>\r\n");
      out.write("										        </div>\r\n");
      out.write("										    </div>\r\n");
      out.write("										    \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-dollar-sign fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">매수\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                           \r\n");
      out.write("                                                \r\n");
      out.write("                                                    <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">\r\n");
      out.write("                                   		 \r\n");
      out.write("												<input type=\"number\" id=\"volume1\" name=\"volume\" min=1 value=1>\r\n");
      out.write("												<a href=\"javascript:buy('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.stocks_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\r\n");
      out.write("												매수</a>\r\n");
      out.write("										\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("						 <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-warning shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">매도\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                           \r\n");
      out.write("                                                \r\n");
      out.write("                                                    <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">\r\n");
      out.write("                                   		 \r\n");
      out.write("												<input type=\"number\" id=\"volume2\" name=\"volume\" min=1 value=1>\r\n");
      out.write("												<a href=\"javascript:sell('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.stocks_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\r\n");
      out.write("												매도</a>\r\n");
      out.write("										\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("						\r\n");
      out.write("                        <!-- Pending Requests Card Example -->\r\n");
      out.write("                        \r\n");
      out.write("                       \r\n");
      out.write("                    <!-- Content Row -->\r\n");
      out.write("\r\n");
      out.write("                  <!-- Pie Chart -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <!-- Card Header - Dropdown -->\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">자산/부채 비율 그래프</h6>\r\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\r\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\r\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card Body -->\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"chart-pie pt-4 pb-2\">\r\n");
      out.write("                                        <canvas id=\"myPieChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mt-4 text-center small\">\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-primary\"></i> 자산총계\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-success\"></i> 부채총계\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                     \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("						<!-- 그래프2 -->\r\n");
      out.write("                      <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <!-- Card Header - Dropdown -->\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">거래량 그래프</h6>\r\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\r\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\r\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card Body -->\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"chart-pie pt-4 pb-2\">\r\n");
      out.write("                                        <canvas id=\"myPieChart2\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mt-4 text-center small\">\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-primary\"></i> 전체 거래량\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-success\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.company_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 거래량\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                     \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     						  <span> Details of ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.company_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write(" 						  In Millions of KRW(except for dept ratio) <br>\r\n");
      out.write(" 						  <br>\r\n");
      out.write(" 						  more details <br>\r\n");
      out.write(" 						  <a target = \"_blank\" rel = \"nofollow\" href = \"https://www.investing.com/\">https://www.investing.com/</a>\r\n");
      out.write(" 						  \r\n");
      out.write(" 						  </span> \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  <!-- 카드 -->\r\n");
      out.write(" 						  <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-primary shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">\r\n");
      out.write("                                               	Asset</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.asset}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("                                            \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">\r\n");
      out.write("                                               	Debt</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.debt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">Sales\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                                <div class=\"col-auto\">\r\n");
      out.write("                                                    <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.sales}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">\r\n");
      out.write("                                               	Debt Ratio</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.debt/stocks.asset*100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write(" 						  \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"row\">\r\n");
      out.write("                    					\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                         \r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("					                        <!-- 검색 -->\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("		\r\n");
      out.write("					\r\n");
      out.write("                    <!-- 테이블 -->\r\n");
      out.write("					 <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Page Heading -->\r\n");
      out.write("                    <h1 class=\"h3 mb-2 text-gray-800\">Transaction History</h1>\r\n");
      out.write("                    <p class=\"mb-4\">Following table is for showing all investors' transaction data.\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <!-- DataTales Example -->\r\n");
      out.write("                    <div class=\"card shadow mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3\">\r\n");
      out.write("                            <h6 class=\"m-0 font-weight-bold text-primary\">주식시장 거래내역</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>거래번호</th>\r\n");
      out.write("                                            <th>투자자명</th>\r\n");
      out.write("                                            <th>주식번호</th>\r\n");
      out.write("                                            <th>구매개수</th>\r\n");
      out.write("                                            <th>거래가격</th>\r\n");
      out.write("                                            <th>매도/매수</th>\r\n");
      out.write("\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                 \r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                            		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; Your Website 2021</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"/login\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"/resources/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 그래프1 -->\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("	 \r\n");
      out.write("	 <script type=\"text/javascript\">\r\n");
      out.write("	 Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif';\r\n");
      out.write("	 Chart.defaults.global.defaultFontColor = '#858796';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 var ctx = document.getElementById(\"myPieChart\");\r\n");
      out.write("	 var myPieChart = new Chart(ctx, {\r\n");
      out.write("	   type: 'doughnut',\r\n");
      out.write("	   data: {\r\n");
      out.write("	     labels: [\"자산총계\", \"부채총계\"],\r\n");
      out.write("	     datasets: [{\r\n");
      out.write("	       data: [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.asset}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.debt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("],\r\n");
      out.write("	       backgroundColor: ['#4e73df', '#1cc88a'],\r\n");
      out.write("	       hoverBackgroundColor: ['#2e59d9', '#17a673'],\r\n");
      out.write("	       hoverBorderColor: \"rgba(234, 236, 244, 1)\",\r\n");
      out.write("	     }],\r\n");
      out.write("	   },\r\n");
      out.write("	   options: {\r\n");
      out.write("	     maintainAspectRatio: false,\r\n");
      out.write("	     tooltips: {\r\n");
      out.write("	       backgroundColor: \"rgb(255,255,255)\",\r\n");
      out.write("	       bodyFontColor: \"#858796\",\r\n");
      out.write("	       borderColor: '#dddfeb',\r\n");
      out.write("	       borderWidth: 1,\r\n");
      out.write("	       xPadding: 15,\r\n");
      out.write("	       yPadding: 15,\r\n");
      out.write("	       displayColors: false,\r\n");
      out.write("	       caretPadding: 10,\r\n");
      out.write("	     },\r\n");
      out.write("	     legend: {\r\n");
      out.write("	       display: false\r\n");
      out.write("	     },\r\n");
      out.write("	     cutoutPercentage: 80,\r\n");
      out.write("	   },\r\n");
      out.write("	 });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("		<!-- 그래프2 -->\r\n");
      out.write("	 <script type=\"text/javascript\">\r\n");
      out.write("	 Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif';\r\n");
      out.write("	 Chart.defaults.global.defaultFontColor = '#858796';\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	 var ctx = document.getElementById(\"myPieChart2\");\r\n");
      out.write("	 var myPieChart = new Chart(ctx, {\r\n");
      out.write("	   type: 'doughnut',\r\n");
      out.write("	   data: {\r\n");
      out.write("	     labels: [\"전체거래량\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stocks.company_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("거래량\"],\r\n");
      out.write("	     datasets: [{\r\n");
      out.write("	       data: [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalvolume}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volume}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("],\r\n");
      out.write("	       backgroundColor: ['#4e73df', '#1cc88a'],\r\n");
      out.write("	       hoverBackgroundColor: ['#2e59d9', '#17a673'],\r\n");
      out.write("	       hoverBorderColor: \"rgba(234, 236, 244, 1)\",\r\n");
      out.write("	     }],\r\n");
      out.write("	   },\r\n");
      out.write("	   options: {\r\n");
      out.write("	     maintainAspectRatio: false,\r\n");
      out.write("	     tooltips: {\r\n");
      out.write("	       backgroundColor: \"rgb(255,255,255)\",\r\n");
      out.write("	       bodyFontColor: \"#858796\",\r\n");
      out.write("	       borderColor: '#dddfeb',\r\n");
      out.write("	       borderWidth: 1,\r\n");
      out.write("	       xPadding: 15,\r\n");
      out.write("	       yPadding: 15,\r\n");
      out.write("	       displayColors: false,\r\n");
      out.write("	       caretPadding: 10,\r\n");
      out.write("	     },\r\n");
      out.write("	     legend: {\r\n");
      out.write("	       display: false\r\n");
      out.write("	     },\r\n");
      out.write("	     cutoutPercentage: 80,\r\n");
      out.write("	   },\r\n");
      out.write("	 });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("		function buy(stocks_code, price){\r\n");
      out.write("	  	  let buy = document.createElement('form'); \r\n");
      out.write("		  let volume = document.getElementById(\"volume1\");\r\n");
      out.write("		  \r\n");
      out.write("		  let code = document.createElement('input');\r\n");
      out.write("		  code.setAttribute('type', 'hidden');\r\n");
      out.write("		  code.setAttribute('name', 'stocks_code');\r\n");
      out.write("		  code.setAttribute('value', stocks_code);\r\n");
      out.write("		  \r\n");
      out.write("		  let pri = document.createElement('input');\r\n");
      out.write("		  pri.setAttribute('type', 'hidden');\r\n");
      out.write("		  pri.setAttribute('name', 'price');\r\n");
      out.write("		  pri.setAttribute('value', price);\r\n");
      out.write("		  \r\n");
      out.write("		  buy.appendChild(volume);\r\n");
      out.write("		  buy.appendChild(code);\r\n");
      out.write("		  buy.appendChild(pri);\r\n");
      out.write("		  \r\n");
      out.write("		  buy.setAttribute('method', 'POST');\r\n");
      out.write("		  buy.setAttribute('action', '/buy'); \r\n");
      out.write("		  document.body.appendChild(buy);\r\n");
      out.write("		  buy.submit();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function sell(stocks_code, price){\r\n");
      out.write("		  	  let sell = document.createElement('form'); \r\n");
      out.write("			  let volume = document.getElementById(\"volume2\");\r\n");
      out.write("			  \r\n");
      out.write("			  let code = document.createElement('input');\r\n");
      out.write("			  code.setAttribute('type', 'hidden');\r\n");
      out.write("			  code.setAttribute('name', 'stocks_code');\r\n");
      out.write("			  code.setAttribute('value', stocks_code);\r\n");
      out.write("			  \r\n");
      out.write("			  let pri = document.createElement('input');\r\n");
      out.write("			  pri.setAttribute('type', 'hidden');\r\n");
      out.write("			  pri.setAttribute('name', 'price');\r\n");
      out.write("			  pri.setAttribute('value', price);\r\n");
      out.write("			  \r\n");
      out.write("			  sell.appendChild(volume);\r\n");
      out.write("			  sell.appendChild(code);\r\n");
      out.write("			  sell.appendChild(pri);\r\n");
      out.write("			  \r\n");
      out.write("			  sell.setAttribute('method', 'POST');\r\n");
      out.write("			  sell.setAttribute('action', '/sell'); \r\n");
      out.write("			  document.body.appendChild(sell);\r\n");
      out.write("			  sell.submit();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 <!-- 랜덤 -->\r\n");
      out.write("   <script>\r\n");
      out.write("        let generateNum = document.querySelector(\".countNumber\");\r\n");
      out.write("        let button = document.querySelector(\".generate\");\r\n");
      out.write("\r\n");
      out.write("        function generator(){\r\n");
      out.write("            const randomNum = ((Math.round(Math.random() * 100 - 50)/100) + (Math.round(Math.random() * 100 - 50)/100)).toFixed(2);\r\n");
      out.write("            //Math.random 0~1 사이의 난수 생성\r\n");
      out.write("            //Math.floor 소수점을 내림시켜 정수로 만듦\r\n");
      out.write("            generateNum.innerHTML = randomNum + '%';\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        button.addEventListener(\"click\", generator);\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/indexDetail.jsp(477,30) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/indexDetail.jsp(477,30) '${requestScope.trading}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.trading}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/indexDetail.jsp(477,30) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("trading");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		   							 <tr>\r\n");
            out.write("		     						   <td bgcolor=\"\">\r\n");
            out.write("		         						   <p align=\"center\">\r\n");
            out.write("			      						      <span style=\"font-size:12pt;\">\r\n");
            out.write("			       						     	\r\n");
            out.write("			       						     	<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.trading_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("			 						           </span>\r\n");
            out.write("		  						          </p>\r\n");
            out.write("		  						      </td>\r\n");
            out.write("		  						      \r\n");
            out.write("								        <td bgcolor=\"\">\r\n");
            out.write("								            <p align=\"center\">\r\n");
            out.write("							            	<span style=\"font-size:12pt;\">\r\n");
            out.write("							            		\r\n");
            out.write("							             		<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("		        						     </span>\r\n");
            out.write("								             </p>\r\n");
            out.write("								        </td>\r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("		  						      <td bgcolor=\"\">\r\n");
            out.write("											<p align=\"center\">\r\n");
            out.write("												<span style=\"font-size:12pt;\">\r\n");
            out.write("					\r\n");
            out.write("												<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.stocks_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("											</span>\r\n");
            out.write("											</p>\r\n");
            out.write("		  						      </td>\r\n");
            out.write("		  						      \r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("								           <td bgcolor=\"\">\r\n");
            out.write("								            <p align=\"center\">\r\n");
            out.write("							            	<span style=\"font-size:12pt;\">\r\n");
            out.write("							            	\r\n");
            out.write("							             		<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.volume}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("		        						     </span>\r\n");
            out.write("								             </p>\r\n");
            out.write("								        </td>\r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("								           <td bgcolor=\"\">\r\n");
            out.write("								            <p align=\"center\">\r\n");
            out.write("							            	<span style=\"font-size:12pt;\">\r\n");
            out.write("							            		\r\n");
            out.write("							             		<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.trading_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("		        						     </span>\r\n");
            out.write("								             </p>\r\n");
            out.write("								        </td>\r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("								           <td bgcolor=\"\">\r\n");
            out.write("								            <p align=\"center\">\r\n");
            out.write("							            	<span style=\"font-size:12pt;\">\r\n");
            out.write("							            		\r\n");
            out.write("							             		<b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trading.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b>\r\n");
            out.write("		        						     </span>\r\n");
            out.write("								             </p>\r\n");
            out.write("								        </td>\r\n");
            out.write("								        \r\n");
            out.write("								        \r\n");
            out.write("									    </tr>\r\n");
            out.write("									   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
