/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-05 01:16:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1683009320000L));
    _jspx_dependants.put("jar:file:/C:/multi/06.spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/step14_JavaConfig/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1682639668000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682400015840L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"/resources/css/layout.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_style_header -->\r\n");
      out.write("<header>\r\n");
      out.write("  <h1>Servlet / JSP</h1>\r\n");
      out.write("  <p>Dept Practice Header</p>\r\n");
      out.write("  <div align=right>\r\n");
      out.write("  	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- action, method -->\r\n");
      out.write("<form action=\"/login\" method=\"POST\">\r\n");
      out.write("	<table align=\"center\" cellpadding=\"5\" cellspacing=\"1\" width=\"600\" border=\"1\">\r\n");
      out.write("	    <tr>\r\n");
      out.write("	        <td width=\"1220\" height=\"20\" colspan=\"2\" bgcolor=\"#336699\">\r\n");
      out.write("	            <p align=\"center\">\r\n");
      out.write("	            	<font color=\"white\" size=\"3\">\r\n");
      out.write("	            		<b>로그인</b>\r\n");
      out.write("	            	</font>\r\n");
      out.write("	            </p>\r\n");
      out.write("	        </td>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	    <tr>\r\n");
      out.write("	        <td width=\"150\" height=\"20\">\r\n");
      out.write("	            <p align=\"center\"><b><span style=\"font-size:12pt;\">사원번호</span></b></p>\r\n");
      out.write("	        </td>\r\n");
      out.write("	        <td width=\"450\" height=\"20\" align=\"center\">\r\n");
      out.write("	        	<b>\r\n");
      out.write("	        		<span style=\"font-size:12pt;\">\r\n");
      out.write("	        			<input id=\"empno\" type=\"text\" name=\"empno\" size=\"30\">\r\n");
      out.write("	        		</span>\r\n");
      out.write("	        		<br/>\r\n");
      out.write("	        		<span id=\"empnoMsg\" style=\"font-size:8pt;\"></span>\r\n");
      out.write("	        	</b>\r\n");
      out.write("	        </td>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	    <tr>\r\n");
      out.write("	        <td width=\"150\" height=\"20\">\r\n");
      out.write("	            <p align=\"center\"><b><span style=\"font-size:12pt;\">사  원  명</span></b></p>\r\n");
      out.write("	        </td>\r\n");
      out.write("	        <td width=\"450\" height=\"20\" align=\"center\">\r\n");
      out.write("	        	<b>\r\n");
      out.write("	        		<span style=\"font-size:12pt;\">\r\n");
      out.write("	        			<!-- input 박스 -->\r\n");
      out.write("	        			<input type=\"text\" name=\"ename\" size=\"30\">\r\n");
      out.write("	        		</span>\r\n");
      out.write("	        	</b>\r\n");
      out.write("	        </td>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	    <tr>\r\n");
      out.write("	        <td width=\"150\" height=\"20\">\r\n");
      out.write("	            <p><b><span style=\"font-size:12pt;\">&nbsp;</span></b></p>\r\n");
      out.write("	        </td>\r\n");
      out.write("	        <td width=\"450\" height=\"20\" align=\"center\">\r\n");
      out.write("	        	<b>\r\n");
      out.write("	        		<span style=\"font-size:12pt;\">\r\n");
      out.write("						<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("					</span>\r\n");
      out.write("				</b>\r\n");
      out.write("			</td>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("<div align=center>\r\n");
      out.write("	<span style=\"font-size:12pt;\"><input type=\"button\" value=\"메인으로\" onclick=\"location.href='/getDeptList.do'\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("  <p>copyright 2023</p>\r\n");
      out.write("  <p>Dept Practice</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("const inputEmpno = document.getElementById('empno');\r\n");
      out.write("const empnoMsg = document.getElementById('empnoMsg');\r\n");
      out.write("	\r\n");
      out.write("inputEmpno.addEventListener('blur', () => {\r\n");
      out.write("	axios.get('http://localhost:8082/api/emp/'+inputEmpno.value)\r\n");
      out.write("		.then(response => {\r\n");
      out.write("			empnoMsg.innerHTML = '존재하는 회원입니다. 로그인을 진행해주세요.';\r\n");
      out.write("		})\r\n");
      out.write("		.catch(error => {\r\n");
      out.write("			empnoMsg.innerHTML = error.response.data;\r\n");
      out.write("		})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(10,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("	  <span style=\"font-size:12pt;\"><input type=\"button\" value=\"로그인\" onclick=\"location.href='/login'\"></span>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/header.jsp(13,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님</span> &nbsp;&nbsp;&nbsp;  \r\n");
          out.write("	  <span style=\"font-size:12pt;\"><input type=\"button\" value=\"로그아웃\" onclick=\"location.href='/logout'\"></span>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
